### ISSUE TITLE
Hello！

### ISSUE THREAD

**Issue by zhoushen1** [fordevoted/UtilityIR#1]
The allweather dataset is a dataset mixed with raindrop, snow and rainstreak. When you train, do you manually divide them into three folders? Thank you!

**Comment by fordevoted** [comment]
> The allweather dataset is a dataset mixed with raindrop, snow and rainstreak. When you train, do you manually divide them into three folders? Thank you!

Yes, we manually devide allweather dataset into three individual folders, and you can refer to dataset.py for the folder structure.

**Comment by zhoushen1** [comment]
Is there 18,069 images in allweather, 818 of which are raindrops, 9,001 snows and 8,250 rainstreaks?

**Comment by Youqiang-Gui** [comment]
i CANT Duplicate result，I think there is something wrong

**Comment by fordevoted** [comment]
Please refer to #4 for more information related to this issue, if there are still any problems, please provide your experiment detail and feel free to let me know. Thanks.
