### ISSUE TITLE
Can you tell me what datasets you used？

### ISSUE THREAD

**Issue by 1001kathy** [fordevoted/UtilityIR#2]
hi author，I‘m interested about your work and wants to ask what datasets your used in raindrop,rainsteak,snow tasks. 
Meanwhile, a brief tree structure about your datasets will be helpful! 
Thanks,I'm looking forward to your reply. ^_^

**Comment by fordevoted** [comment]
> hi author，I‘m interested about your work and wants to ask what datasets your used in raindrop,rainsteak,snow tasks.
> Meanwhile, a brief tree structure about your datasets will be helpful!
> Thanks,I'm looking forward to your reply. ^_^

Hi Kathy, 
   We use AllWeather dataset for training, you may refer to `Experiments` Section in our paper for more detail. The tree structure of dataset is shown below:

    AllWeather
    ｜train
     |├── raindrop
    ｜ | ├── input
    ｜ | ├── gt
     |├── rainstreak
    ｜ | ├── input
    ｜ | ├── gt
     |├── snow
    ｜ | ├── input
    ｜ | ├── gt
    ｜Val
     |├── …
     ….


You can find and change the path in `dataset.py` line 73-113. 
Thanks.
