### ISSUE TITLE
Why the test size is 40?

### ISSUE THREAD

**Issue by liu645liu** [fordevoted/UtilityIR#3]
Thank you for your work, but I have the following questions. About the test set of this working code, your code path shows rain streak, raindrop, and snow three data sets, they include many photos but why did the test.py only test 40 photos each time? Can you explain why?

**Comment by fordevoted** [comment]
> Thank you for your work, but I have the following questions. About the test set of this working code, your code path shows rain streak, raindrop, and snow three data sets, they include many photos but why did the test.py only test 40 photos each time? Can you explain why?

Thank you for your interest. It only tests 40 photos since the length of DegradationTestDataset is set to 40 (dataset.py line#239), which is for quick debugging.
 I just revised the code, and now the testing code should go through the whole dataset. Thank you for your friendly reminder
