### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by liu645liu** [fordevoted/UtilityIR#4]
Hello author, I am very interested in your research and have reproduced your code, but the results are significantly different from the data in the paper. I would like to ask if your dataset was manually classified, and if there is a problem with my dataset classification. Could you please provide the well classified dataset you used? Thank you for your work!

**Comment by fordevoted** [comment]
> Hello author, I am very interested in your research and have reproduced your code, but the results are significantly different from the data in the paper. I would like to ask if your dataset was manually classified, and if there is a problem with my dataset classification. Could you please provide the well classified dataset you used? Thank you for your work!

Could you reproduce the result using provided pretrained weights? Besides, please provide your dataset setup detail then I can help you debug, thanks.

**Comment by liu645liu** [comment]
I have retrained the model myself. I think even if it is not the same as the indicator in your paper, the gap should not be that big. It is 7 or 8 points different from the results in your paper. Below is my dataset setup：
  allweather:
    test|
        raindrop|
           gt
           input
       raindtreak|
           gt
           input
       snow|
          gt
          input
    train|  
        raindrop|
             gt
             input
         raindtreak|
             gt
             input
         snow|
            gt
            input

**Comment by fordevoted** [comment]
> I have retrained the model myself. I think even if it is not the same as the indicator in your paper, the gap should not be that big. It is 7 or 8 points different from the results in your paper. Below is my dataset setup： allweather: test| raindrop| gt input raindtreak| gt input snow| gt input train| raindrop| gt input raindtreak| gt input snow| gt input

The training and testing datasets are uploaded to https://huggingface.co/datasets/YuweiChen/UtilityIR_allweather/tree/main, please check it, thanks.

**Comment by Youqiang-Gui** [comment]
> I have retrained the model myself. I think even if it is not the same as the indicator in your paper, the gap should not be that big. It is 7 or 8 points different from the results in your paper. Below is my dataset setup： allweather: test| raindrop| gt input raindtreak| gt input snow| gt input train| raindrop| gt input raindtreak| gt input snow| gt input

I got the same result as you.
